/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Label;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author LVIS MACUA
 */
public class ViewTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewTelaPrincipal
     */
    public ViewTelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        jlUsuario.setText(this.getUser_log());

        
        
    } 
 
    static String user_log;
   
    public static String getUser_log() {
        return user_log;
    }

    public static void setUser_log(String user_log) {
        ViewTelaPrincipal.user_log = user_log;
    }

//    private ViewTelaPrincipal() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    
    
     
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jlUsuario = new javax.swing.JLabel();
        jlUsuarioIcon = new javax.swing.JLabel();
        jlcondicao = new javax.swing.JLabel();
        jldata = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbClientes = new javax.swing.JButton();
        jbProdutos = new javax.swing.JButton();
        jbVendas = new javax.swing.JButton();
        jbUsuarios = new javax.swing.JButton();
        jbRelatorioVendas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemVendas = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Desktop.setBackground(new java.awt.Color(153, 153, 153));
        Desktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuario.setText("Usuário");
        Desktop.add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 60, -1, 20));

        jlUsuarioIcon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlUsuarioIcon.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuarioIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usu.png"))); // NOI18N
        Desktop.add(jlUsuarioIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, -1, 30));

        jlcondicao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlcondicao.setForeground(new java.awt.Color(255, 255, 255));
        jlcondicao.setText("Perfil");
        Desktop.add(jlcondicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, -1, -1));

        jldata.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jldata.setForeground(new java.awt.Color(255, 255, 255));
        jldata.setText("Data");
        Desktop.add(jldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 60, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/barraMenuVerde.png"))); // NOI18N
        Desktop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 40));

        jbClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbcliente1.png"))); // NOI18N
        jbClientes.setBorder(null);
        jbClientes.setBorderPainted(false);
        jbClientes.setContentAreaFilled(false);
        jbClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbcliente.png"))); // NOI18N
        jbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClientesActionPerformed(evt);
            }
        });
        Desktop.add(jbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jbProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbprodutos1.png"))); // NOI18N
        jbProdutos.setBorder(null);
        jbProdutos.setBorderPainted(false);
        jbProdutos.setContentAreaFilled(false);
        jbProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbProdutos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbprodutos2.png"))); // NOI18N
        jbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutosActionPerformed(evt);
            }
        });
        Desktop.add(jbProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jbVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbvendas.png"))); // NOI18N
        jbVendas.setBorder(null);
        jbVendas.setBorderPainted(false);
        jbVendas.setContentAreaFilled(false);
        jbVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVendas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbvendas2.png"))); // NOI18N
        jbVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendasActionPerformed(evt);
            }
        });
        Desktop.add(jbVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jbUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbusuarios.png"))); // NOI18N
        jbUsuarios.setBorder(null);
        jbUsuarios.setBorderPainted(false);
        jbUsuarios.setContentAreaFilled(false);
        jbUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbusuarios2.png"))); // NOI18N
        jbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuariosActionPerformed(evt);
            }
        });
        Desktop.add(jbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jbRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbrelatoriovendas.png"))); // NOI18N
        jbRelatorioVendas.setBorder(null);
        jbRelatorioVendas.setBorderPainted(false);
        jbRelatorioVendas.setContentAreaFilled(false);
        jbRelatorioVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRelatorioVendas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jbrelatorioVendas 1.png"))); // NOI18N
        jbRelatorioVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioVendasActionPerformed(evt);
            }
        });
        Desktop.add(jbRelatorioVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/blouse-2597205_1920.jpg"))); // NOI18N
        jLabel1.setText("ghg");
        Desktop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/document.png"))); // NOI18N
        jMenu1.setText("Arquivos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_add.png"))); // NOI18N
        jMenu2.setText("Cadastros");

        jMenuItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCliente.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer.png"))); // NOI18N
        jMenuItemCliente.setText("Clientes");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCliente);

        jMenuItemProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProduto.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delivery-box.png"))); // NOI18N
        jMenuItemProduto.setText("Produtos");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemProduto);

        jMenuItemUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/group.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuários");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUsuario);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-cart.png"))); // NOI18N
        jMenu3.setText("Movimentos");

        jMenuItemVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVendas.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/jmenuvendas.png"))); // NOI18N
        jMenuItemVendas.setText("Vendas");
        jMenuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemVendas);

        jMenuBar1.add(jMenu3);

        jMenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdff.png"))); // NOI18N
        jMenuRelatorio.setText("Relatórios");

        jMenuItem3.setText("jMenuItem3");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItem3);

        jMenuBar1.add(jMenuRelatorio);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/idioma.png"))); // NOI18N
        jMenu5.setText("Idioma");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mz.png"))); // NOI18N
        jMenuItem7.setText("Português");
        jMenu5.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usa.png"))); // NOI18N
        jMenuItem8.setText("Inglês");
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Jogo");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Totoloto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu6.setBackground(new java.awt.Color(255, 255, 255));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        jMenu6.setText("Ajuda");

        jMenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSobre.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logotipoTendinha.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemSobre);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClientesActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false); 
        new ViewCliente(this).setVisible(true);
       
      

    }//GEN-LAST:event_jbClientesActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new ViewCliente(this).setVisible(true);
       
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuariosActionPerformed
        // TODO add your handling code here:
         this.setEnabled(false);
         new ViewUsuario(this).setVisible(true);
    }//GEN-LAST:event_jbUsuariosActionPerformed

    private void jbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutosActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new ViewProduto(this).setVisible(true);
    }//GEN-LAST:event_jbProdutosActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
       new ViewProduto(this).setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
       new ViewUsuario(this).setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jbVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendasActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new ViewVendas(this).setVisible(true);
    }//GEN-LAST:event_jbVendasActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Date dataSistema= new Date();
        SimpleDateFormat formato=new SimpleDateFormat("dd-MM-YYYY");
        jldata.setText(formato.format(dataSistema));
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new ViewSobre(this).setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new ViewVendas(this).setVisible(true);
    }//GEN-LAST:event_jMenuItemVendasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new ProgressGame(this).setVisible(true);
//        this.setEnabled(false);
//        new ViewJogoTotoloto(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioVendasActionPerformed
        // TODO add your handling code here:
       this.setEnabled(false);
       new ViewListaVendas(this).setVisible(true);
    }//GEN-LAST:event_jbRelatorioVendasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new ViewClienteDeletado(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {  
                
                new ViewTelaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenuItem jMenuItemVendas;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JButton jbClientes;
    private javax.swing.JButton jbProdutos;
    private javax.swing.JButton jbRelatorioVendas;
    public static javax.swing.JButton jbUsuarios;
    private javax.swing.JButton jbVendas;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JLabel jlUsuarioIcon;
    private javax.swing.JLabel jlcondicao;
    private javax.swing.JLabel jldata;
    // End of variables declaration//GEN-END:variables
}
