/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author LVIS MACUA
 */
public class ViewTelaErrou extends javax.swing.JFrame {

    /**
     * Creates new form ViewTelaErrou
     */
    ViewJogoTotoloto viewAnterior;
    public ViewTelaErrou(String palpite,int numeroSorteado) {
        initComponents();
        setLocationRelativeTo(null);
        jtfPalpite.setText(palpite);
        jtfSorteado.setText(String.valueOf(numeroSorteado));
    }

    private ViewTelaErrou() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public ViewTelaErrou(ViewJogoTotoloto viewAnterior) {
        this();
        this.viewAnterior=viewAnterior;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfPalpite = new javax.swing.JTextField();
        jtfSorteado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 270));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(null);

        jtfPalpite.setEditable(false);
        jtfPalpite.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfPalpite.setForeground(new java.awt.Color(0, 153, 102));
        jtfPalpite.setBorder(null);
        jPanel1.add(jtfPalpite);
        jtfPalpite.setBounds(300, 140, 140, 30);

        jtfSorteado.setEditable(false);
        jtfSorteado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfSorteado.setForeground(new java.awt.Color(0, 153, 102));
        jtfSorteado.setBorder(null);
        jtfSorteado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSorteadoActionPerformed(evt);
            }
        });
        jPanel1.add(jtfSorteado);
        jtfSorteado.setBounds(300, 200, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/telaErrouogo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 271);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSorteadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSorteadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSorteadoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.viewAnterior.setEnabled(true );
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTelaErrou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTelaErrou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTelaErrou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTelaErrou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTelaErrou().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfPalpite;
    private javax.swing.JTextField jtfSorteado;
    // End of variables declaration//GEN-END:variables
}
